version: '3.3'

services:
    mysql_db:
        container_name: mysql
        image: mysql:5.7
        volumes:
            - ./mysql/data:/docker-entrypoint-initdb.d
#            - ./mysql/data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: d2_db
            MYSQL_USER: mysql_user
            MYSQL_PASSWORD: mysql_user
            MYSQL_ROOT_PASSWORD: mysql_root
            MYSQL_ROOT_HOST: '%'
            MYSQL_USER_HOST: '%'
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        ports:
            - "3306:3306"

    spring:
        container_name: spring
        build: ./d2-spring/.
        ports:
            - "8080:8080"
        restart: on-failure
        depends_on:
            - mysql_db

    spring-backup:
        container_name: spring-backup
        build: ./d2-spring/.
        ports:
            - "8090:8090"
        restart: on-failure
        depends_on:
            - mysql_db

    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "81:81"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
