version: '3.3'

services:
    mysql:
        container_name: mysql
        image: mysql:5.7
        volumes:
            - ./mysql/data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: test_db
            MYSQL_USER: test
            MYSQL_ROOT_PASSWORD: test
            MYSQL_ROOT_HOST: '%'
        ports:
            - "3306:3306"

    spring:
        container_name: spring
        build: ./d2-spring/.
        ports:
            - "8080:8080"
        depends_on:
            - mysql