version: '3.3'

services:
    mysql_db:
        container_name: mysql
        image: mysql:5.7
        volumes:
            - ./mysql/data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: d2_db
            MYSQL_USER: mysql_user
            MYSQL_PASSWORD: mysql_user
            MYSQL_ROOT_PASSWORD: mysql_root
            MYSQL_ROOT_HOST: '%'
            MYSQL_USER_HOST: '%'
        ports:
            - "3306:3306"

    spring:
        container_name: spring
        build: ./d2-spring/.
        ports:
            - "8080:8080"
        depends_on:
            - mysql_db